# Generated by Django 4.1.10 on 2023-07-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_dataer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
        migrations.DeleteModel(
            name='dataer',
        ),
        migrations.DeleteModel(
            name='users_data',
        ),
    ]
