# Generated by Django 4.1.10 on 2023-07-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyApp', '0004_delete_data_delete_dataer_delete_users_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=250)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
