# Generated by Django 4.1.10 on 2023-07-19 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_data',
            name='transport',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
