# Generated by Django 4.1.10 on 2023-07-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_users_data_transport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users_data',
        ),
    ]
